nextest: do not use on aarch64-linux due to unknown error
It fails in GitHub like this:

```
lzallright-nextest> Running phase: checkPhase
lzallright-nextest> ++ command cargo nextest run --cargo-profile release
lzallright-nextest>    Compiling lzokay-sys v0.2.4 (/build/source/lzokay-sys)
lzallright-nextest>    Compiling lzallright v0.2.4 (/build/source)
lzallright-nextest>     Finished release [optimized] target(s) in 37.80s
lzallright-nextest> error: creating test list failed
lzallright-nextest> Caused by:
lzallright-nextest>   for `lzallright`, command `/build/source/target/release/deps/lzallright-e47eb44249232760 --list --format terse` exited with code 1
lzallright-nextest> --- stdout:
lzallright-nextest> --- stderr:
lzallright-nextest> ---
error: builder for '/nix/store/6axkw1x8abpm9fjg037wb45y8nnypm05-lzallright-nextest-0.2.4.drv' failed with exit code 104;
```